### ISSUE TITLE
IndexError: index out of range in self

### ISSUE THREAD

**Issue by dingtom** [xiaoyu2018/TextSum#1]
同学，跑你的代码在微调的时候遇到了这个问题，请问你有遇到吗，能提供一下解决思路不😁
Traceback (most recent call last):
  File "C:\myFile\TextSum-main\source\go.py", line 101, in <module>
    main()
  File "C:\myFile\TextSum-main\source\go.py", line 22, in main
    pm.FineTune(net, tkz)
  File "C:\myFile\TextSum-main\source\pretrained_models.py", line 76, in FineTune
    l = net(input_ids=input_ids, attention_mask=attention_mask, labels=labels).loss
  File "C:\software\Anaconda3\envs\tomding\lib\site-packages\torch\nn\modules\module.py", line 1103,
in _call_impl
    return forward_call(*input, **kwargs)
  File "C:\software\Anaconda3\envs\tomding\lib\site-packages\transformers\models\bart\modeling_bart.p
y", line 1320, in forward
    outputs = self.model(
  File "C:\software\Anaconda3\envs\tomding\lib\site-packages\torch\nn\modules\module.py", line 1103,
in _call_impl
    return forward_call(*input, **kwargs)
  File "C:\software\Anaconda3\envs\tomding\lib\site-packages\transformers\models\bart\modeling_bart.p
y", line 1193, in forward
    encoder_outputs = self.encoder(
  File "C:\software\Anaconda3\envs\tomding\lib\site-packages\torch\nn\modules\module.py", line 1103,
in _call_impl
    return forward_call(*input, **kwargs)
  File "C:\software\Anaconda3\envs\tomding\lib\site-packages\transformers\models\bart\modeling_bart.p
y", line 775, in forward
    embed_pos = self.embed_positions(input_shape)
  File "C:\software\Anaconda3\envs\tomding\lib\site-packages\torch\nn\modules\module.py", line 1103,
in _call_impl
    return forward_call(*input, **kwargs)
  File "C:\software\Anaconda3\envs\tomding\lib\site-packages\transformers\models\bart\modeling_bart.p
y", line 124, in forward
    return super().forward(positions + self.offset)
  File "C:\software\Anaconda3\envs\tomding\lib\site-packages\torch\nn\modules\sparse.py", line 159, i
n forward
    return F.embedding(
  File "C:\software\Anaconda3\envs\tomding\lib\site-packages\torch\nn\functional.py", line 2044, in e
mbedding
    return torch.embedding(weight, input, padding_idx, scale_grad_by_freq, sparse)
IndexError: index out of range in self

**Comment by xiaoyu2018** [comment]
bartembedding最大只支持到1024。使用预训练模型bart时，settings.py 中SOURCE_THRESHOLD不能超过1024

**Comment by xiaoyu2018** [comment]
> 同学，跑你的代码在微调的时候遇到了这个问题，请问你有遇到吗，能提供一下解决思路不😁 Traceback (most recent call last): File "C:\myFile\TextSum-main\source\go.py", line 101, in main() File "C:\myFile\TextSum-main\source\go.py", line 22, in main pm.FineTune(net, tkz) File "C:\myFile\TextSum-main\source\pretrained_models.py", line 76, in FineTune l = net(input_ids=input_ids, attention_mask=attention_mask, labels=labels).loss File "C:\software\Anaconda3\envs\tomding\lib\site-packages\torch\nn\modules\module.py", line 1103, in _call_impl return forward_call(*input, **kwargs) File "C:\software\Anaconda3\envs\tomding\lib\site-packages\transformers\models\bart\modeling_bart.p y", line 1320, in forward outputs = self.model( File "C:\software\Anaconda3\envs\tomding\lib\site-packages\torch\nn\modules\module.py", line 1103, in _call_impl return forward_call(*input, **kwargs) File "C:\software\Anaconda3\envs\tomding\lib\site-packages\transformers\models\bart\modeling_bart.p y", line 1193, in forward encoder_outputs = self.encoder( File "C:\software\Anaconda3\envs\tomding\lib\site-packages\torch\nn\modules\module.py", line 1103, in _call_impl return forward_call(*input, **kwargs) File "C:\software\Anaconda3\envs\tomding\lib\site-packages\transformers\models\bart\modeling_bart.p y", line 775, in forward embed_pos = self.embed_positions(input_shape) File "C:\software\Anaconda3\envs\tomding\lib\site-packages\torch\nn\modules\module.py", line 1103, in _call_impl return forward_call(*input, **kwargs) File "C:\software\Anaconda3\envs\tomding\lib\site-packages\transformers\models\bart\modeling_bart.p y", line 124, in forward return super().forward(positions + self.offset) File "C:\software\Anaconda3\envs\tomding\lib\site-packages\torch\nn\modules\sparse.py", line 159, i n forward return F.embedding( File "C:\software\Anaconda3\envs\tomding\lib\site-packages\torch\nn\functional.py", line 2044, in e mbedding return torch.embedding(weight, input, padding_idx, scale_grad_by_freq, sparse) IndexError: index out of range in self

**Comment by xiaoyu2018** [comment]
> 同学，跑你的代码在微调的时候遇到了这个问题，请问你有遇到吗，能提供一下解决思路不😁 Traceback (most recent call last): File "C:\myFile\TextSum-main\source\go.py", line 101, in main() File "C:\myFile\TextSum-main\source\go.py", line 22, in main pm.FineTune(net, tkz) File "C:\myFile\TextSum-main\source\pretrained_models.py", line 76, in FineTune l = net(input_ids=input_ids, attention_mask=attention_mask, labels=labels).loss File "C:\software\Anaconda3\envs\tomding\lib\site-packages\torch\nn\modules\module.py", line 1103, in _call_impl return forward_call(*input, **kwargs) File "C:\software\Anaconda3\envs\tomding\lib\site-packages\transformers\models\bart\modeling_bart.p y", line 1320, in forward outputs = self.model( File "C:\software\Anaconda3\envs\tomding\lib\site-packages\torch\nn\modules\module.py", line 1103, in _call_impl return forward_call(*input, **kwargs) File "C:\software\Anaconda3\envs\tomding\lib\site-packages\transformers\models\bart\modeling_bart.p y", line 1193, in forward encoder_outputs = self.encoder( File "C:\software\Anaconda3\envs\tomding\lib\site-packages\torch\nn\modules\module.py", line 1103, in _call_impl return forward_call(*input, **kwargs) File "C:\software\Anaconda3\envs\tomding\lib\site-packages\transformers\models\bart\modeling_bart.p y", line 775, in forward embed_pos = self.embed_positions(input_shape) File "C:\software\Anaconda3\envs\tomding\lib\site-packages\torch\nn\modules\module.py", line 1103, in _call_impl return forward_call(*input, **kwargs) File "C:\software\Anaconda3\envs\tomding\lib\site-packages\transformers\models\bart\modeling_bart.p y", line 124, in forward return super().forward(positions + self.offset) File "C:\software\Anaconda3\envs\tomding\lib\site-packages\torch\nn\modules\sparse.py", line 159, i n forward return F.embedding( File "C:\software\Anaconda3\envs\tomding\lib\site-packages\torch\nn\functional.py", line 2044, in e mbedding return torch.embedding(weight, input, padding_idx, scale_grad_by_freq, sparse) IndexError: index out of range in self

在settings.py 中，设置SOURCE_THRESHOLD=1024
